kind: pipeline
name: frontend

steps:
- name: build
  image: alpine
  group: one
  commands:
  - sleep 10
  - echo done
  - date

- name: build2
  image: alpine
  group: one
  commands:
  - sleep 10
  - echo done
  - date

---
kind: pipeline
name: backend

steps:
- name: build
  image: alpine
  commands:
  - sleep 10
  - echo done
  - date

services:
- name: redis
  image: redis
  ports:
  - 6379
  
- name: mongo
  image: mongo:4
  command: [ --smallfiles ]
  ports:
  - 27017

---
kind: pipeline
name: after

steps:
- name: test-mongodb
  image: mongo:4
  commands:
  - sleep 5
  - mongo --host mongo --eval "db.version()"

- name: test-redis
  image: redis
  commands:
  - sleep 5
  - redis-cli -h redis ping
  - redis-cli -h redis set FOO bar
  - redis-cli -h redis get FOO

- name: notify
  image: alpine
  commands:
  - sleep 10
  - echo done
  - date

depends_on:
- frontend
- backend
