kind: pipeline
name: frontend

steps:
- name: build
  image: alpine
  group: one
  commands:
  - sleep 10
  - echo done

- name: build2
  image: alpine
  group: one
  commands:
  - sleep 10
  - echo done

---
kind: pipeline
name: backend

steps:
- name: build
  image: alpine
  commands:
  - sleep 10
  - echo done

services:
- name: redis
  image: redis

---
kind: pipeline
name: after

steps:
- name: notify
  image: alpine
  commands:
  - sleep 10
  - echo done

depends_on:
- frontend
- backend
