kind: pipeline
name: frontend

steps:
- name: build
  image: alpine
  group: one
  commands:
  - sleep 10
  - echo done
  - date

- name: build2
  image: alpine
  group: one
  commands:
  - sleep 10
  - echo done
  - date

---
kind: pipeline
name: backend

steps:
- name: build
  image: alpine
  commands:
  - sleep 10
  - echo done
  - date

services:
- name: mongo
  image: mongo:4
  command: [ --smallfiles ]
  ports:
  - 27017

- name: test-mongodb
  image: mongo:4
  commands:
  - sleep 5
  - mongo --host mongo --eval "db.version()"
  - sh scripts/write_mongo.sh
  - sh scripts/read_mongo.sh
---
kind: pipeline
name: after

steps:
- name: notify
  image: alpine
  commands:
  - sleep 10
  - echo done
  - date

- name: test-mongod-writes
  image: mongo:4
  commands:
  - echo "testing mongodb writes"
  - sh scripts/read_mongo.sh

- name: test-mongodb-reads
  image: mongo:4
  commands:
  - echo "testing mongodb reads"
  - sh scripts/read_mongo.sh

depends_on:
- frontend
- backend
